### ISSUE TITLE
2016-04-27: April Meetup with Symfony UG at TBC

### ISSUE THREAD

**Issue by driesvints** [phpantwerp/meetups#1]
**Details**

- Meetup page: http://www.meetup.com/phpantwerp/events/229991355/
- Joind.in page:

**Todo**

- [ ] Arrange venue
- [ ] Announce on Twitter
- [ ] Announce on Meetup.com
- [ ] Add schedule to Meetup.com page

**Talk 1**

- [ ] Confirm Speaker
- [ ] Title & Abstract
- [ ] Speaker Bio
- [ ] Talk Length

**Talk 2**

- [ ] Confirm Speaker
- [ ] Title & Abstract
- [ ] Speaker Bio
- [ ] Talk Length

**Comment by driesvints** [comment]
Cancelled
