### ISSUE TITLE
2016-05-24: May Meetup at MCS

### ISSUE THREAD

**Issue by driesvints** [phpantwerp/meetups#2]
**Details**

- Meetup page: http://www.meetup.com/phpantwerp/events/228775387/
- Joind.in page: https://legacy.joind.in/event/view/5800

**Todo**

- [x] Arrange venue
- [x] Announce on Twitter
- [x] Announce on Meetup.com
- [ ] Add schedule to Meetup.com page

**Talk 1**

- [x] Confirm Speaker
- [x] Title & Abstract
- [x] Speaker Bio
- [x] Talk Length

**Talk 2**

- [x] Confirm Speaker
- [x] Title & Abstract
- [x] Speaker Bio
- [x] Talk Length
