### ISSUE TITLE
2016-07-27: July Meetup at TBD

### ISSUE THREAD

**Issue by driesvints** [phpantwerp/meetups#4]
**Details**

- Meetup page: http://www.meetup.com/phpantwerp/events/228775392/
- Joind.in page:

**Todo**

- [ ] Arrange venue
- [ ] Announce on Twitter
- [ ] Announce on Meetup.com
- [ ] Add schedule to Meetup.com page

**Talk 1**

- [x] Confirm Speaker
- [x] Title & Abstract
- [x] Speaker Bio
- [x] Talk Length

**Talk 2**

- [x] Confirm Speaker
- [x] Title & Abstract
- [x] Speaker Bio
- [x] Talk Length
