### ISSUE TITLE
2016-09-28: September Meetup at TBD

### ISSUE THREAD

**Issue by driesvints** [phpantwerp/meetups#5]
**Details**

- [x] Meetup page: http://www.meetup.com/phpantwerp/events/228775399/
- [x] Joind.in page: https://legacy.joind.in/event/view/6022

**Todo**

- [ ] Arrange venue
- [ ] Announce on Twitter
- [ ] Announce on Meetup.com
- [ ] Add schedule to Meetup.com page

**Talk 1**

- [x] Confirm Speaker
- [x] Title & Abstract
- [x] Speaker Bio
- [x] Talk Length

**Talk 2**

- [x] Confirm Speaker
- [x] Title & Abstract
- [x] Speaker Bio
- [x] Talk Length

**Comment by veewee** [comment]
@driesvints,

Are you still looking for a venue?
We would love to host this one at the Phpro offices in Kontich.

**Comment by ntrogh** [comment]
@driesvints Are you still looking for a second talk? I'd suggest a session on how to run PHP on Azure.
-Nick

**Comment by tombevers** [comment]
@driesvints,

Any news on the venue? We would love to host this meetup at the PHPro offices in Kontich.

**Comment by driesvints** [comment]
@ntrogh heya! We currently already have two talks for September planned. I can still set you up for our December meetup if you want to give your talk. Let me know! 

@veewee @tombevers is PHP Pro perhaps interested in hosting our december meetup?

http://www.meetup.com/phpantwerp/events/233732033/

**Comment by ntrogh** [comment]
@driesvints Definitely interested in doing a talk for the December meetup!

**Comment by driesvints** [comment]
@ntrogh awesome! You can send me an email with your talk title, description, length and your speaker bio to dries.vints@gmail.com :)

**Comment by tombevers** [comment]
@driesvints December is okay for us.

**Comment by driesvints** [comment]
@tombevers awesome! I'll send you an email to discuss further :)
