### ISSUE TITLE
2016-11-30: November Meetup at TBD

### ISSUE THREAD

**Issue by driesvints** [phpantwerp/meetups#6]
**Details**

- Meetup page: http://www.meetup.com/phpantwerp/events/228775407/
- Joind.in page:

**Todo**

- [x] Arrange venue
- [ ] Announce on Twitter
- [x] Announce on Meetup.com
- [ ] Add schedule to Meetup.com page

**Talk 1**

- [x] Confirm Speaker
- [x] Title & Abstract
- [x] Speaker Bio
- [x] Talk Length

**Talk 2**

- [x] Confirm Speaker
- [x] Title & Abstract
- [x] Speaker Bio
- [x] Talk Length
