### ISSUE TITLE
2016-08-31: August Meetup at These Days

### ISSUE THREAD

**Issue by freekmurze** [phpantwerp/meetups#7]
**Details**

- [x] Meetup page: http://www.meetup.com/phpantwerp/events/232022844/
- [x] Joind.in page: 

**Todo**

- [X] Arrange venue
- [x] Announce on Twitter
- [X] Announce on Meetup.com
- [X] Add schedule to Meetup.com page

**Talk 1: API development**

- [X] Confirm Speaker
- [X] Title & Abstract
- [x] Speaker Bio
- [x] Talk Length

**Talk 2: AWQ**

- [X] Confirm Speaker
- [X] Title & Abstract
- [X] Speaker Bio
- [X] Talk Length
