### ISSUE TITLE
Spotcrowd 

### ISSUE THREAD

**Issue by jgmio** [phpantwerp/meetups#8]
**Details**

We are just kicking off our production phase and would love to host your meet-ups.
This allows us to network with local developers while you get an awesome venue to host from.
Sounds like a win-win no?

- [ ] Meetup page:
- [ ] Joind.in page:

**Todo**

- [ ] Arrange venue : 23rd Floor of the KBC Tower
- [ ] Announce on Twitter
- [ ] Announce on Meetup.com
- [ ] Add schedule to Meetup.com page

**Talk 1**

- [ ] Confirm Speaker
- [ ] Title & Abstract
- [ ] Speaker Bio
- [ ] Talk Length

**Talk 2**

- [ ] Confirm Speaker
- [ ] Title & Abstract
- [ ] Speaker Bio
- [ ] Talk Length
